//
//  globalParam.h
//  Beltality
//
//  Created by Mac Mini on 01.11.10.
//  Copyright 2010 JoyPeople. All rights reserved.
//

extern int SCREEN_WIDTH;
extern int SCREEN_HEIGHT;
extern int SCREEN_WIDTH_HALF;
extern int SCREEN_HEIGHT_HALF;

//-------GUI--------------
extern float BUTTON_DOWN_WAIT;
//------------------------

extern BOOL GAME_IS_PLAYING;
extern BOOL GAME_EASTER;

#define GAME_VERSION 1.f

#define GAME_RATE_URL @"http://itunes.apple.com/WebObjects/MZStore.woa/wa/viewContentsUserReviews?id=515220537&onlyLatestVersion=true&pageNumber=0&sortOrdering=1&type=Purple+Software"
#define URL_GIFT_THIS_APP @"https://buy.itunes.apple.com/WebObjects/MZFinance.woa/wa/giftSongsWizard?gift=1&salableAdamId=515220537&productType=C&pricingParameter=STDQ"
#define URL_FACEBOOK @"http://www.facebook.com/FDGEntertainment"
#define URL_TWITTER @"http://twitter.com/#!/FDG_Games"
#define URL_VIDEO @"http://www.youtube.com/FDGGames"

#define FRAME_RATE 60.f
#define TIME_STEP 1/FRAME_RATE

#define MTP_RATIO 30
#define PTM_RATIO 1/MTP_RATIO

#define GAME_STATE_NONE				0x00000000
#define GAME_STATE_ALWAYS			0xffffffff
#define GAME_STATE_MENU				0x00000001
#define GAME_STATE_GAME				0x00000002
#define GAME_STATE_LEVELSCREEN		0x00000004
#define GAME_STATE_CREDITS			0x00000008
#define GAME_STATE_HIGHSCORE		0x00000100
#define GAME_STATE_HELP				0x00000200
#define GAME_STATE_GAMEOVER			0x00000400
#define GAME_STATE_LEVELFINISH		0x00000800
#define GAME_STATE_GAMEFINISH		0x00010000
#define GAME_STATE_GAMEPREPARE		0x00020000
#define GAME_STATE_SHOWROOM			0x00040000
#define GAME_STATE_PACKAGESCREEN	0x00080000
#define GAME_STATE_MARKETSCREEN		0x01000000
#define GAME_STATE_GAMEPAUSE		0x02000000
#define GAME_STATE_STORYSCREEN      0x04000000
#define GAME_STATE_LOADINGSCREEN    0x08000000


#define GAME_STATE_MOREGAMES        0x00000300

#define UPGRADE_LEVEL_COUNT 5

#define BONUS_COINS 115
#define BONUS_SLOWMOTION 5
#define BONUS_ACCELERATION 20
#define BONUS_APOCALYPSE 25
#define BONUS_GODMODE 30
#define BONUS_RANDOM_RANGE 33

#define BONUS_ACCELERATION_POWER_DEFAULT 0.2f
#define BONUS_ACCELERATION_POWER_ADD_COEFF 0.07f

#define BONUS_ACCELERATION_DELAY_DEFAULT 1
#define BONUS_ACCELERATION_DELAY_MAX 5
#define BONUS_ACCELERATION_DELAY_ADD_COEFF 0.2f

#define BONUS_GODMODE_TIME_DEFAULT 2
#define BONUS_GODMODE_TIME_MAX 4
#define BONUS_GODMODE_TIME_ADD_COEFF 0.4f

#define BONUS_GET_CHANCE_DEFAULT 0.05f
#define BONUS_GET_CHANCE_ADD_COEFF 0.03f

#define COINS_GET_CHANCE_DEFAULT 0.05f
#define COINS_GET_CHANCE_ADD_COEFF 0.03f

#define GRAVITATION_DEFAULT 0.10f
#define GRAVITATION_ADD_COEFF -0.01f

#define SPEEDWALL_ACCELERATION_DEFAULT 0.15f
#define SPEEDWALL_ACCELERATION_MAX 0.75f
#define SPEEDWALL_ACCELERATION_ADD_COEFF 0.10f

#define SPEEDWALL_DECCELERARION_DEFAULT -0.06f
#define SPEEDWALL_DECCELERARION_MIN -0.01f
#define SPEEDWALL_DECCELERARION_ADD_COEFF 0.01f

#define SPEEDWALL_DELAYSHOWINGCOEFF_DEFAULT 2
#define SPEEDWALL_DELAYSHOWINGCOEFF_MAX 12
#define SPEEDWALL_DELAYSHOWINGCOEFF_ADD_COEFF 1

#define PLAYER_MAGNET_DISTANDE_DEFAULT 50  
#define PLAYER_MAGNET_DISTANDE_MAX 264
#define PLAYER_MAGNET_DISTANDE_ADD_COEFF 40

#define PLAYER_MAGNET_POWER_DEFAULT 2
#define PLAYER_MAGNET_POWER_MAX 8
#define PLAYER_MAGNET_POWER_ADD_COEFF 3

#define PLAYER_SPEED_LIMIT_DEFAULT 30
#define PLAYER_SPEED_LIMIT_ADD_COEFF 10

#define PLAYER_BOMB_SLOW_DEFAULT 1.f
#define PLAYER_BOMB_SLOW_ADD_COEFF 0.5f

#define GODMODE_AFTERCRASH_TIME_DEFAULT 0.5f
#define GODMODE_AFTERCRASH_TIME_MAX 3.0f
#define GODMODE_AFTERCRASH_TIME_ADD_COEFF 0.4f


//----------------------------------------------------------------
// GAMEPLAY CONST
//----------------------------------------------------------------

#define bombTouchSize 50
#define elementSize 45
#define elementRadius 22.5f

#define screenPlayerPositionX 160
#define screenPlayerPositionY 320

#define ZCOORD_OBJECTS 100

#define Z_EFFECT 500
#define Z_GUI 5000

//static public var ropeStartDistance:Number = 1;

// Rate me popup:
#define NOTIFICATION_RATEME_FONT_SIZE_IPAD 15
#define NOTIFICATION_RATEME_FONT_SIZE_IPHONE 14

#define NOTIFICATION_RATEME_FONT_SIZE_MOD_DE 0.9f
#define NOTIFICATION_RATEME_FONT_SIZE_MOD_ES 0.7f
#define NOTIFICATION_RATEME_FONT_SIZE_MOD_RU 0.8f
#define NOTIFICATION_RATEME_FONT_SIZE_MOD_PT 0.8f
#define NOTIFICATION_RATEME_FONT_SIZE_MOD_IT 0.9f
#define NOTIFICATION_RATEME_FONT_SIZE_MOD_FR 0.9f

#define NOTIFICATION_IAPBUY_FONT_SIZE_MOD_DE 1.0f
#define NOTIFICATION_IAPBUY_FONT_SIZE_MOD_ES 1.0f
#define NOTIFICATION_IAPBUY_FONT_SIZE_MOD_RU 1.0f
#define NOTIFICATION_IAPBUY_FONT_SIZE_MOD_PT 1.0f
#define NOTIFICATION_IAPBUY_FONT_SIZE_MOD_IT 1.0f
#define NOTIFICATION_IAPBUY_FONT_SIZE_MOD_FR 1.0f

#define NOTIFICATION_IAPBUYMENU_FONT_SIZE_MOD_DE 1.0f
#define NOTIFICATION_IAPBUYMENU_FONT_SIZE_MOD_ES 1.0f
#define NOTIFICATION_IAPBUYMENU_FONT_SIZE_MOD_RU 0.9f
#define NOTIFICATION_IAPBUYMENU_FONT_SIZE_MOD_PT 1.0f
#define NOTIFICATION_IAPBUYMENU_FONT_SIZE_MOD_IT 1.0f
#define NOTIFICATION_IAPBUYMENU_FONT_SIZE_MOD_FR 0.9f

#define NOTIFICATION_UI_ALERT_VISIBLE @"UIAlertViewShown"
#define NOTIFICATION_UI_ALERT_HIDDEN @"UIAlertViewHidden"

#define NOTIFICATION_RATEME_ID 1
#define NOTIFICATION_IAPBUY_ID 2
#define NOTIFICATION_IAPBUYMENU_ID 3